server:
  port: 9090
#  error:
#    include-stacktrace: never

logging:
  level:
    org:
      springframework:
        security: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: 'library-client'
            client-secret: '9584640c-3804-4dcd-997b-93593cfb9ea7'
            authorization-grant-type: authorization_code
            redirect-uri: 'http://localhost:9090/login/oauth2/code/keycloak'
            scope: 'openid'
        provider:
          keycloak:
            issuer-uri: http://localhost:8081/auth/realms/workshop
            user-name-attribute: name
