management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

spring:
  data:
    mongodb:
      port: 40495
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    default-property-inclusion: non_null
  mongodb:
    embedded:
      version: '4.0.12'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/auth/realms/workshop
server:
  error:
    include-stacktrace: never
  port: 9091
